2021-07-18 02:33:24,622 INFO    MainThread:34769 [internal.py:wandb_internal():88] W&B internal server running at pid: 34769, started at: 2021-07-18 02:33:24.621923
2021-07-18 02:33:24,624 DEBUG   HandlerThread:34769 [handler.py:handle_request():124] handle_request: check_version
2021-07-18 02:33:24,625 INFO    WriterThread:34769 [datastore.py:open_for_write():80] open: /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/run-35u06kgg.wandb
2021-07-18 02:33:24,628 DEBUG   SenderThread:34769 [sender.py:send():179] send: header
2021-07-18 02:33:24,628 DEBUG   SenderThread:34769 [sender.py:send_request():193] send_request: check_version
2021-07-18 02:33:24,858 DEBUG   SenderThread:34769 [sender.py:send():179] send: run
2021-07-18 02:33:25,124 INFO    SenderThread:34769 [dir_watcher.py:__init__():168] watching files in: /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/files
2021-07-18 02:33:25,124 INFO    SenderThread:34769 [sender.py:_start_run_threads():716] run started: 35u06kgg with start time 1626575603
2021-07-18 02:33:25,125 DEBUG   SenderThread:34769 [sender.py:send():179] send: summary
2021-07-18 02:33:25,125 DEBUG   HandlerThread:34769 [handler.py:handle_request():124] handle_request: run_start
2021-07-18 02:33:25,126 INFO    SenderThread:34769 [sender.py:_save_file():841] saving file wandb-summary.json with policy end
2021-07-18 02:33:25,132 DEBUG   HandlerThread:34769 [meta.py:__init__():39] meta init
2021-07-18 02:33:25,132 DEBUG   HandlerThread:34769 [meta.py:__init__():53] meta init done
2021-07-18 02:33:25,132 DEBUG   HandlerThread:34769 [meta.py:probe():210] probe
2021-07-18 02:33:25,139 DEBUG   HandlerThread:34769 [meta.py:_setup_git():200] setup git
2021-07-18 02:33:25,158 DEBUG   HandlerThread:34769 [meta.py:_setup_git():207] setup git done
2021-07-18 02:33:25,158 DEBUG   HandlerThread:34769 [meta.py:_save_pip():57] save pip
2021-07-18 02:33:25,159 DEBUG   HandlerThread:34769 [meta.py:_save_pip():71] save pip done
2021-07-18 02:33:25,159 DEBUG   HandlerThread:34769 [meta.py:_save_conda():78] save conda
2021-07-18 02:33:26,128 INFO    Thread-8  :34769 [dir_watcher.py:_on_file_created():216] file/dir created: /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/files/conda-environment.yaml
2021-07-18 02:33:26,129 INFO    Thread-8  :34769 [dir_watcher.py:_on_file_created():216] file/dir created: /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/files/requirements.txt
2021-07-18 02:33:26,130 INFO    Thread-8  :34769 [dir_watcher.py:_on_file_created():216] file/dir created: /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/files/wandb-summary.json
2021-07-18 02:33:27,572 WARNING MainThread:34769 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-07-18 02:33:27,575 DEBUG   HandlerThread:34769 [meta.py:_save_conda():86] save conda done
2021-07-18 02:33:27,576 DEBUG   HandlerThread:34769 [meta.py:probe():252] probe done
2021-07-18 02:33:27,581 DEBUG   SenderThread:34769 [sender.py:send():179] send: files
2021-07-18 02:33:27,581 INFO    SenderThread:34769 [sender.py:_save_file():841] saving file wandb-metadata.json with policy now
2021-07-18 02:33:28,126 INFO    Thread-8  :34769 [dir_watcher.py:_on_file_modified():229] file/dir modified: /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/files/conda-environment.yaml
2021-07-18 02:33:28,126 INFO    Thread-8  :34769 [dir_watcher.py:_on_file_created():216] file/dir created: /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/files/wandb-metadata.json
2021-07-18 02:33:28,202 INFO    Thread-11 :34769 [upload_job.py:push():137] Uploaded file /tmp/tmpt_2fzyfowandb/ul7q36v6-wandb-metadata.json
2021-07-18 02:33:32,663 WARNING MainThread:34769 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-07-18 02:33:32,663 ERROR   MainThread:34769 [internal.py:wandb_internal():150] Internal process interrupted.
2021-07-18 02:33:33,583 INFO    WriterThread:34769 [datastore.py:close():288] close: /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/run-35u06kgg.wandb
2021-07-18 02:33:33,583 INFO    SenderThread:34769 [sender.py:finish():945] shutting down sender
2021-07-18 02:33:33,583 INFO    SenderThread:34769 [dir_watcher.py:finish():282] shutting down directory watcher
2021-07-18 02:33:33,588 INFO    HandlerThread:34769 [handler.py:finish():638] shutting down handler
2021-07-18 02:33:34,128 INFO    SenderThread:34769 [dir_watcher.py:finish():312] scan: /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/files
2021-07-18 02:33:34,129 INFO    SenderThread:34769 [dir_watcher.py:finish():318] scan save: /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/files/wandb-metadata.json wandb-metadata.json
2021-07-18 02:33:34,129 INFO    SenderThread:34769 [dir_watcher.py:finish():318] scan save: /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/files/config.yaml config.yaml
2021-07-18 02:33:34,129 INFO    SenderThread:34769 [dir_watcher.py:finish():318] scan save: /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/files/wandb-summary.json wandb-summary.json
2021-07-18 02:33:34,130 INFO    SenderThread:34769 [dir_watcher.py:finish():318] scan save: /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/files/conda-environment.yaml conda-environment.yaml
2021-07-18 02:33:34,136 INFO    SenderThread:34769 [dir_watcher.py:finish():318] scan save: /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/files/requirements.txt requirements.txt
2021-07-18 02:33:34,147 INFO    SenderThread:34769 [file_pusher.py:finish():177] shutting down file pusher
2021-07-18 02:33:34,147 INFO    SenderThread:34769 [file_pusher.py:join():182] waiting for file pusher
2021-07-18 02:33:34,800 INFO    Thread-12 :34769 [upload_job.py:push():137] Uploaded file /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/files/config.yaml
2021-07-18 02:33:34,889 INFO    Thread-13 :34769 [upload_job.py:push():137] Uploaded file /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/files/wandb-summary.json
2021-07-18 02:35:33,609 ERROR   FileStreamThread:34769 [file_stream.py:_thread_except_body():311] generic exception in filestream thread
Traceback (most recent call last):
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 307, in _thread_except_body
    self._thread_body()
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 281, in _thread_body
    self._handle_response(
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 320, in _handle_response
    raise response
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 419, in request_with_retry
    response.raise_for_status()
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/files/hsyang1222/cluster_gan/35u06kgg/file_stream
2021-07-18 02:35:44,207 INFO    Thread-14 :34769 [upload_job.py:push():137] Uploaded file /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/files/conda-environment.yaml
2021-07-18 02:37:55,302 INFO    Thread-15 :34769 [upload_job.py:push():137] Uploaded file /home/hsyang/workspace/20210715_cluster_gan/wandb/run-20210718_023323-35u06kgg/files/requirements.txt
2021-07-18 02:37:55,952 ERROR   SenderThread:34769 [file_stream.py:finish():395] FileStream exception
Traceback (most recent call last):
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 307, in _thread_except_body
    self._thread_body()
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 281, in _thread_body
    self._handle_response(
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 320, in _handle_response
    raise response
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 419, in request_with_retry
    response.raise_for_status()
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/files/hsyang1222/cluster_gan/35u06kgg/file_stream
2021-07-18 02:37:55,954 ERROR   MainThread:34769 [internal.py:wandb_internal():159] Thread SenderThread:
Traceback (most recent call last):
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 55, in run
    self._run()
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 106, in _run
    self._finish()
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/wandb/sdk/internal/internal.py", line 295, in _finish
    self._sm.finish()
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 956, in finish
    self._fs.finish(self._exit_code)
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 397, in finish
    six.reraise(*self._exc_info)
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 307, in _thread_except_body
    self._thread_body()
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 281, in _thread_body
    self._handle_response(
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 320, in _handle_response
    raise response
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/wandb/sdk/internal/file_stream.py", line 419, in request_with_retry
    response.raise_for_status()
  File "/opt/conda/envs/stylegan2/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/files/hsyang1222/cluster_gan/35u06kgg/file_stream
2021-07-18 02:37:57,968 INFO    MainThread:34769 [internal.py:handle_exit():78] Internal process exited
